name: Deploy Website to Local Docker Nginx

on:
  push:
    branches:
      - main   # Trigger when code is pushed to main branch

jobs:
  deploy:
    runs-on: self-hosted   # Run on your local machine (requires self-hosted runner)

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Copy files into Docker Nginx container
    - name: Deploy site to Docker Nginx
      run: |
        echo "Copying site files into Docker container..."
        docker cp mysite/. mysite-nginx:/usr/share/nginx/html
        echo "Reloading Nginx..."
        docker exec mysite-nginx nginx -s reload
