name: Deploy Vite React App to Local Docker Nginx

on:
  push:
    branches:
      - main   # Trigger when code is pushed to main branch

jobs:
  deploy:
    runs-on: self-hosted   # Must be your local machine with Docker

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies & build project
    - name: Build Vite project
      run: |
        npm install
        npm run build   # Output goes to dist/

    # Step 3: Copy build files into Docker container
    - name: Deploy to Docker Nginx
      run: |
        docker cp dist/. mysite-nginx:/usr/share/nginx/html
        docker exec mysite-nginx nginx -s reload
